export { default as NotFoundPage } from './NotFoundPage'
export { default as MainPage } from './Main/MainPage'
export { default as SearchPage } from './Search/SearchPage'
export { default as LoginPage } from './Login/LoginPage'
export { default as JoinPage } from './Login/JoinPage'